name: pulgueta_nequi_dart
description: SDK de la comunidad de Nequi para Dart
version: 0.0.1
repository: https://github.com/pulgueta/nequi-dart-sdk

environment:
  sdk: ^3.5.2

dev_dependencies:
  commitlint_cli: ^0.7.1
  husky: ^0.1.7
  lints: ^4.0.0
  test: ^1.24.0
