name: nequi_dart_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  commitlint_cli: ^0.7.1
  husky: ^0.1.7
  lints: ^4.0.0
  test: ^1.24.0
