name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    secrets:
      GH_TOKEN:
        required: false

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1.6.5

      - name: Get Dependencies
        run: dart pub get

      - name: Analyze
        run: dart analyze .

      - name: Check Format
        run: dart format . --output=none --set-exit-if-changed

      - name: Run tests
        run: dart test --reporter expanded
